import type { DependencyGraph } from "./dependencyGraph.js";
import { summarizeRepository } from "./summarizer.js";
import type { RepoScanResult } from "../types.js";
import {
  escapeMarkdownCell,
  escapeMermaidLabel,
} from "../utils/security.js";

export function buildArchitectureMarkdown(
  scan: RepoScanResult,
  graph: DependencyGraph,
): string {
  const summary = summarizeRepository(scan);
  const safeName = escapeMermaidLabel(scan.name);
  const lines: string[] = [
    `# Architecture: ${escapeMarkdownCell(scan.name)}`,
    "",
    "> Generated by [repo-clarity](https://github.com/Sosuke1006/repo-clarity). Re-run with `repo-clarity generate architecture`.",
    "",
    "## Overview",
    "",
    summary.description,
    "",
    summary.architecture,
    "",
    "## Repository layout",
    "",
    "```",
    ".",
  ];

  for (const item of scan.structure.slice(0, 20)) {
    lines.push(`├── ${escapeMarkdownCell(item)}`);
  }
  lines.push("```", "");

  if (scan.entryPoints.length > 0) {
    lines.push("## Entry points", "");
    for (const ep of scan.entryPoints) {
      lines.push(`- \`${escapeMarkdownCell(ep)}\``);
    }
    lines.push("");
  }

  lines.push("## Dependency graph", "");
  if (graph.nodes.length === 0) {
    lines.push("_No manifest dependencies detected._", "");
  } else {
    const manifestRel = graph.manifestPath
      ? graph.manifestPath
          .replace(scan.rootPath, "")
          .replace(/^[/\\]/, "")
          .replace(/\\/g, "/")
      : null;
    lines.push(
      `Ecosystem: **${graph.ecosystem}**${manifestRel ? ` (\`${escapeMarkdownCell(manifestRel)}\`)` : ""}`,
      "",
      "| Package | Version | Kind |",
      "| ------- | ------- | ---- |",
    );
    const shown = graph.nodes.slice(0, 40);
    for (const node of shown) {
      lines.push(
        `| ${escapeMarkdownCell(node.name)} | ${escapeMarkdownCell(node.version ?? "—")} | ${node.kind} |`,
      );
    }
    if (graph.nodes.length > 40) {
      lines.push("", `_…and ${graph.nodes.length - 40} more dependencies._`);
    }
    lines.push("");
    lines.push("```mermaid");
    lines.push("flowchart LR");
    lines.push(`  root["${safeName}"]`);
    for (const node of shown.slice(0, 15)) {
      const id = node.name.replace(/[^a-zA-Z0-9]/g, "_");
      const label = escapeMermaidLabel(node.name);
      lines.push(`  root --> ${id}["${label}"]`);
    }
    lines.push("```", "");
  }

  lines.push("## Tooling", "");
  lines.push(
    `- **Languages:** ${scan.languages.map((l) => l.language).join(", ") || "n/a"}`,
  );
  lines.push(`- **CI:** ${scan.ci.hasCi ? scan.ci.provider : "not detected"}`);
  lines.push(
    `- **Tests:** ${scan.testFrameworks.frameworks.join(", ") || "not detected"}`,
  );
  lines.push("");

  if (summary.devCommands.length > 0) {
    lines.push("## Development commands", "");
    for (const cmd of summary.devCommands) {
      lines.push(`- \`${escapeMarkdownCell(cmd)}\``);
    }
    lines.push("");
  }

  return lines.join("\n").trimEnd() + "\n";
}
